const inventoryItems = [
  {
    id: 1,
    name: "Flower Vase",
    imageUrl: "src/Utils/vase.jfif",
    associatedEventID: [101, 102, 1092, 22039],
    totalOnHand: 15,
    originalPurchaseDate: "2021-01-20",
    timesRented: 8,
    cost: 100.0,
    replacedCount: 2,
    inventoryLocation: "Bin 1",
  },
  {
    id: 2,
    name: "Acrylic Easel",
    imageUrl: "src/Utils/easel.jfif",
    associatedEventID: [103, 334, 2362],
    totalOnHand: 20,
    originalPurchaseDate: "2021-03-15",
    timesRented: 5,
    cost: 150.0,
    replacedCount: 1,
    inventoryLocation: "Bin 4",
  },
  {
    id: 3,
    name: "Acrylic Easel",
    imageUrl: "src/Utils/easel.jfif",
    associatedEventID: [103, 334, 2362],
    totalOnHand: 20,
    originalPurchaseDate: "2021-03-15",
    timesRented: 5,
    cost: 150.0,
    replacedCount: 1,
    inventoryLocation: "Bin 4",
  },
  {
    id: 4,
    name: "Acrylic Easel",
    imageUrl: "src/Utils/easel.jfif",
    associatedEventID: [103, 334, 2362],
    totalOnHand: 20,
    originalPurchaseDate: "2021-03-15",
    timesRented: 5,
    cost: 150.0,
    replacedCount: 1,
    inventoryLocation: "Bin 4",
  },
  {
    id: 5,
    name: "Acrylic Easel",
    imageUrl: "src/Utils/easel.jfif",
    associatedEventID: [103, 334, 2362],
    totalOnHand: 20,
    originalPurchaseDate: "2021-03-15",
    timesRented: 5,
    cost: 150.0,
    replacedCount: 1,
    inventoryLocation: "Bin 4",
  },
  {
    id: 6,
    name: "Acrylic Easel",
    imageUrl: "src/Utils/easel.jfif",
    associatedEventID: [103, 334, 2362],
    totalOnHand: 20,
    originalPurchaseDate: "2021-03-15",
    timesRented: 5,
    cost: 150.0,
    replacedCount: 1,
    inventoryLocation: "Bin 4",
  },
  // Add more items as needed
];

export default inventoryItems;
